Tv/feat/#41
amigoscode/cohort-2-c pull request #56
Opened 2023-06-27 17:50 UTC by thaysvieira

2023-06-27 17:56 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderAddress/CarProviderAddressDTO.java
> +    private Long carProviderId;
remove line 16

2023-06-27 17:56 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderAddress/CarProviderAddress.java
> +@Where(clause = "is_deleted = false")
should extends AbstractAddress

2023-06-28 08:39 UTC, DmitriKonnovNN reviewed
awaiting changes required by Esmaeeil

2023-06-28 13:35 UTC, Esmaeeilenani approved these changes

2023-06-28 14:20 UTC, DmitriKonnovNN requested changes

2023-06-28 14:20 UTC, DmitriKonnovNN commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderAddress/CarProviderAddressDTO.java
> +    private CityDTO cityDTO;
Needs change to: **private CityDTO city;**

2023-06-28 15:35 UTC, DmitriKonnovNN approved these changes
Look absolutely fantastic

2023-06-28 15:35 UTC, merged