#76
amigoscode/cohort-2-c pull request #84
Opened 2023-07-04 23:29 UTC by thaysvieira

As a car providers can create coupons

2023-07-05 01:47 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderUser/CarProviderUserRepository.java
>  @Repository
extends JpaRepository

2023-07-05 01:47 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/CarProviderCouponService.java
> +        Optional<CarProviderUser> carProviderUserOptional = carProviderUserRepository.findByUserId(user.getId());
you should make sure its not null

2023-07-05 08:07 UTC, DmitriKonnovNN requested changes

2023-07-05 08:07 UTC, DmitriKonnovNN commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/VM/CarProviderCouponVM.java
> +    @NotEmpty
VM classes should implement Serializable;
Accordint to Java Object Serialization Specification it is highly recommended "that all serializable classes other than enum types explicitly declare serialVersionUID values".

2023-07-06 16:03 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/CarProviderCouponController.java
> +        carProviderCouponService.save(carProviderCouponVM);
return the create coupon object

2023-07-06 16:03 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/CarProviderCouponService.java
> +        var carProviderUserOptional = carProviderUserRepository.findByUserId(user.getId()).orElseThrow(()-> new NullPointerException(ErrorConstants.INTERNAL));
use APIException class

2023-07-06 16:03 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderUser/CarProviderUserRepository.java
> +public interface CarProviderUserRepository extends JpaRepository<CarProviderUser,Long> {
no need for @Param

2023-07-11 13:42 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/CarProviderCouponRepository.java
>  public interface CarProviderCouponRepository extends CRJpaRepository <CarProviderCoupon, Long> {
extends JpaRepository

2023-07-12 04:06 UTC, Esmaeeilenani commented on carRental/src/main/java/com/amigoscode/chohort2/carRental/carProviderCoupon/CarProviderCouponController.java
> +        return ResponseEntity.accepted().body(carProviderCouponVM);
you should return the created on not what is coming from the client

2023-07-12 04:39 UTC, Esmaeeilenani approved these changes

2023-07-12 14:20 UTC, DmitriKonnovNN approved these changes
LGTM

2023-07-12 14:21 UTC, merged